server:
  port: 8090
logging:
  level:
    org:
      newcih:
        DEBUG
spring:
  datasource:
    driver-class-name: dm.jdbc.driver.DmDriver
    url: jdbc:dm://10.92.225.249/DAMENG
    username: GMP_MM_SDC
    password: GMP_MM_SDC#123
mybatis:
  mapper-locations: classpath:mapper/*.xml

