spring:
  cloud:
    consul:
      discovery:
        enabled: false
  datasource:
    driver-class-name: dm.jdbc.driver.DmDriver
    url: jdbc:dm://10.92.225.249/DAMENG
    username: GMP_MM_SDC
    password: GMP_MM_SDC#123
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 9839
logging:
  pattern:
    console: "%date{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    io.liuguangsheng.galois: debug